server {
  listen 80;
  server_name local.bluff.app;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name local.bluff.app;

  ssl_certificate     /etc/nginx/certs/local.bluff.app.pem;
  ssl_certificate_key /etc/nginx/certs/local.bluff.app-key.pem;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    proxy_pass http://bluff-bb:8080/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
