services:
  bluff-bb:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    volumes:
      - ./backend/src:/app/src
      - ./backend/build.gradle:/app/build.gradle
      - ./backend/settings.gradle:/app/settings.gradle

  bluff-fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - bluff-bb
