FROM eclipse-temurin:21-jdk
WORKDIR /app

COPY gradlew settings.gradle build.gradle ./
COPY gradle ./gradle
RUN chmod +x gradlew && ./gradlew dependencies --no-daemon

COPY src ./src
RUN ./gradlew classes --no-daemon

EXPOSE 8080

COPY entrypoint-dev.sh ./
RUN chmod +x entrypoint-dev.sh
ENTRYPOINT ["./entrypoint-dev.sh"]
